# Generated by Django 4.2.7 on 2023-12-04 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_content', models.CharField(max_length=100)),
                ('alert_category', models.CharField(choices=[('alert_devmate', '데브메이트'), ('alert_chat', '채팅'), ('alert_todo', '할일'), ('alert_schedule', '일정'), ('alert_other', '기타')], max_length=20)),
                ('alert_at', models.DateTimeField(auto_now_add=True)),
                ('alert_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
            },
        ),
    ]
