# Generated by Django 4.2.7 on 2023-12-04 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=100)),
                ('todo_content', models.CharField(blank=True, max_length=200, null=True)),
                ('todo_start', models.DateTimeField()),
                ('todo_end', models.DateTimeField()),
                ('todo_status', models.CharField(default='Todo', max_length=100)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.study')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '할일',
                'verbose_name_plural': '할일',
            },
        ),
    ]
